"""Type stubs for the libpetri PyO3 extension module.

These signatures describe the raw Rust surface exposed by `libpetri._libpetri`.
End users should import from the `libpetri` package (which wraps these), not
this module directly.
"""

from __future__ import annotations

import builtins
import os
from collections.abc import Awaitable, Callable, Iterable, Mapping
from enum import Enum
from typing import Any

# ---------------------------------------------------------------------------
# Exception hierarchy
# ---------------------------------------------------------------------------

class LibpetriError(RuntimeError): ...
class CallbackError(LibpetriError): ...
class StructureError(ValueError): ...

# ---------------------------------------------------------------------------
# Feature flags
# ---------------------------------------------------------------------------

HAS_TOKIO: bool
HAS_Z3: bool
HAS_DEBUG: bool

# ---------------------------------------------------------------------------
# Core model
# ---------------------------------------------------------------------------

class Place:
    def __init__(self, name: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class InputSpec:
    def __repr__(self) -> str: ...

class MatchSpec:
    def __repr__(self) -> str: ...

class OutputSpec:
    def __repr__(self) -> str: ...

class InhibitorArc: ...
class ReadArc: ...
class ResetArc: ...

class Timing:
    def __repr__(self) -> str: ...

class Transition:
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class BuiltinAction(Enum):
    Passthrough = ...
    Fork = ...

class TransitionBuilder:
    def __init__(self, name: str) -> None: ...
    def input(self, spec: InputSpec) -> TransitionBuilder: ...
    def output(self, spec: OutputSpec) -> TransitionBuilder: ...
    def inhibitor(self, arc: InhibitorArc) -> TransitionBuilder: ...
    def read(self, arc: ReadArc) -> TransitionBuilder: ...
    def reset(self, arc: ResetArc) -> TransitionBuilder: ...
    def match_spec(self, spec: MatchSpec) -> TransitionBuilder: ...
    def timing(self, t: Timing) -> TransitionBuilder: ...
    def action(self, action: Callable[..., Any] | BuiltinAction) -> TransitionBuilder: ...
    def priority(self, priority: int) -> TransitionBuilder: ...
    def build(self) -> Transition: ...

class Net:
    @property
    def name(self) -> str: ...
    def compile(self) -> CompiledNet: ...
    def __repr__(self) -> str: ...

class NetBuilder:
    def __init__(self, name: str) -> None: ...
    def place(self, place: Place) -> NetBuilder: ...
    def transition(self, t: Transition) -> NetBuilder: ...
    def compose(
        self,
        instance_name: str,
        subnet: SubnetDef,
        port_bindings: Mapping[str, Place],
    ) -> NetBuilder: ...
    def compose_instance(
        self,
        instance: Instance,
        port_bindings: Mapping[str, Place],
    ) -> NetBuilder: ...
    def build(self) -> Net: ...

class Port:
    @property
    def name(self) -> str: ...
    @property
    def direction(self) -> str: ...
    @property
    def place_name(self) -> str: ...

class Channel:
    @property
    def name(self) -> str: ...
    @property
    def transition_name(self) -> str: ...

class SubnetInstance:
    @property
    def prefix(self) -> str: ...
    @property
    def def_name(self) -> str: ...
    @property
    def transitions(self) -> list[str]: ...
    @property
    def exposed_places(self) -> list[str]: ...
    @property
    def parent_prefix(self) -> str | None: ...

class Instance:
    @property
    def prefix(self) -> str: ...
    @property
    def def_name(self) -> str: ...
    def port_place_name(self, name: str) -> str: ...
    def channel(self, name: str) -> str: ...
    def descriptor(self) -> SubnetInstance: ...
    def bind_actions(self, actions: dict[str, object]) -> Instance: ...

class SubnetDef:
    @property
    def name(self) -> str: ...
    @property
    def port_count(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    def ports(self) -> list[Port]: ...
    def channels(self) -> list[Channel]: ...
    def instantiate(self, prefix: str) -> Instance: ...

class SubnetDefBuilder:
    def __init__(self, name: str) -> None: ...
    def place(self, place: Place) -> SubnetDefBuilder: ...
    def transition(self, t: Transition) -> SubnetDefBuilder: ...
    def input_port(self, name: str, place: Place) -> SubnetDefBuilder: ...
    def output_port(self, name: str, place: Place) -> SubnetDefBuilder: ...
    def inout_port(self, name: str, place: Place) -> SubnetDefBuilder: ...
    def channel(self, name: str, t: Transition) -> SubnetDefBuilder: ...
    def build(self) -> SubnetDef: ...

# ---------------------------------------------------------------------------
# Arc / output / timing factories
# ---------------------------------------------------------------------------

def one(p: Place) -> InputSpec: ...
def match_spec(keys: list[tuple[Place, Callable[[Any], str]]]) -> MatchSpec: ...
def exactly(count: int, p: Place) -> InputSpec: ...
def all_tokens(p: Place) -> InputSpec: ...
def at_least(min: int, p: Place) -> InputSpec: ...
def out_place(p: Place) -> OutputSpec: ...
def and_outputs(children: list[OutputSpec]) -> OutputSpec: ...
def xor_outputs(children: list[OutputSpec]) -> OutputSpec: ...
def timeout_output(after_ms: int, child: OutputSpec) -> OutputSpec: ...
def forward_input(from_: Place, to: Place) -> OutputSpec: ...
def inhibitor(p: Place) -> InhibitorArc: ...
def read(p: Place) -> ReadArc: ...
def reset(p: Place) -> ResetArc: ...
def immediate() -> Timing: ...
def deadline(by_ms: int) -> Timing: ...
def delayed(after_ms: int) -> Timing: ...
def window(earliest_ms: int, latest_ms: int) -> Timing: ...
def exact(at_ms: int) -> Timing: ...

# ---------------------------------------------------------------------------
# Action context (passed to every callback)
# ---------------------------------------------------------------------------

class TransitionContext:
    @property
    def transition_name(self) -> str: ...
    def fresh_name(self) -> str: ...
    def input(self, place_name: str) -> Any: ...
    def inputs(self, place_name: str) -> list[Any]: ...
    def read(self, place_name: str) -> Any: ...
    def reads(self, place_name: str) -> list[Any]: ...
    def output(self, place_name: str, value: Any) -> None: ...
    def output_many(self, place_name: str, values: Iterable[Any]) -> None: ...
    def flush(self) -> None: ...

def captured_event_loop() -> Any: ...

# ---------------------------------------------------------------------------
# Executor
# ---------------------------------------------------------------------------

class ExecutorOptions:
    def __init__(
        self,
        *,
        environment_places: list[str] | None = ...,
        skip_output_validation: bool = ...,
        deadline_tolerance_ms: float | None = ...,
    ) -> None: ...
    @property
    def environment_places(self) -> list[str]: ...
    @property
    def skip_output_validation(self) -> bool: ...
    @property
    def deadline_tolerance_ms(self) -> float | None: ...

class CompiledNet:
    def __init__(self, net: Net) -> None: ...
    @property
    def name(self) -> str: ...
    def run_sync(
        self,
        initial: Mapping[str | Place, Iterable[Any]] | None = ...,
        options: ExecutorOptions | None = ...,
        event_store: InMemoryEventStore | None = ...,
    ) -> dict[str, list[dict[str, Any]]]: ...
    def run_async(
        self,
        initial: Mapping[str | Place, Iterable[Any]] | None = ...,
        options: ExecutorOptions | None = ...,
        event_store: InMemoryEventStore | None = ...,
    ) -> tuple[ExecutorHandle, Awaitable[dict[str, list[dict[str, Any]]]]]: ...

class NetEvent:
    @property
    def type(self) -> str: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def transition_name(self) -> str | None: ...
    @property
    def place_name(self) -> str | None: ...
    def payload(self) -> dict[str, Any]: ...

class EventSubscription:
    def __aiter__(self) -> EventSubscription: ...
    def __anext__(self) -> Any: ...
    def close(self) -> None: ...

class EventStream:
    def __aiter__(self) -> EventStream: ...
    def __anext__(self) -> Any: ...
    def close(self) -> None: ...

class InMemoryEventStore:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def events(
        self,
        *,
        types: Iterable[str] | None = ...,
        transitions: Iterable[str] | None = ...,
        places: Iterable[str] | None = ...,
        limit: int | None = ...,
        offset: int = ...,
    ) -> list[NetEvent]: ...
    def count(self, *, types: Iterable[str] | None = ...) -> int: ...
    def counters(self) -> dict[str, int]: ...
    def failures(self) -> list[NetEvent]: ...
    def subscribe(
        self,
        *,
        types: Iterable[str] | None = ...,
        transitions: Iterable[str] | None = ...,
        places: Iterable[str] | None = ...,
        batch_size: int = ...,
        batch_timeout_ms: int = ...,
        channel_capacity: int = ...,
    ) -> EventSubscription: ...
    def subscribe_stream(
        self,
        *,
        types: Iterable[str] | None = ...,
        transitions: Iterable[str] | None = ...,
        places: Iterable[str] | None = ...,
        channel_capacity: int = ...,
    ) -> EventStream: ...

# Archive feature classes — present only when HAS_ARCHIVE = True.

class SessionArchive:
    @property
    def version(self) -> int: ...
    @property
    def session_id(self) -> str: ...
    @property
    def net_name(self) -> str: ...
    @property
    def event_count(self) -> int: ...
    @property
    def dot_diagram(self) -> str: ...
    @property
    def start_time(self) -> str: ...
    @property
    def end_time(self) -> str | None: ...
    @property
    def tags(self) -> dict[str, str]: ...
    def events(self) -> list[NetEvent]: ...

class SessionArchiveWriter:
    @classmethod
    def write_from_store(
        cls,
        path: str | os.PathLike[str],
        *,
        session_id: str,
        net: Net,
        store: InMemoryEventStore,
        tags: dict[str, str] | None = ...,
    ) -> None: ...

class SessionArchiveReader:
    @classmethod
    def read(cls, path: str | os.PathLike[str]) -> SessionArchive: ...

class ComputedState:
    @property
    def marking(self) -> dict[str, int]: ...
    @property
    def enabled_transitions(self) -> list[str]: ...
    @property
    def in_flight_transitions(self) -> list[str]: ...

class MarkingCache:
    def __init__(self) -> None: ...
    def compute_at(
        self, store: InMemoryEventStore, event_index: int
    ) -> ComputedState: ...
    def invalidate(self) -> None: ...

HAS_ARCHIVE: bool

class ExecutorHandle:
    def inject(self, place: str | Place, value: Any) -> bool: ...
    def inject_many(self, place: str | Place, values: Iterable[Any]) -> bool: ...
    def drain(self) -> bool: ...
    def close(self) -> bool: ...
    @property
    def drained(self) -> bool: ...
    def snapshot(self) -> Awaitable[dict[str, list[dict[str, Any]]]]: ...

# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

class SmtProperty:
    def description(self) -> str: ...

class VerificationResult:
    @property
    def verdict(self) -> str: ...
    @property
    def method(self) -> str | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def report(self) -> str: ...
    @property
    def discovered_invariants(self) -> list[str]: ...
    @property
    def counterexample_transitions(self) -> list[str]: ...
    @property
    def counterexample_trace(self) -> list[dict[str, int]]: ...
    @property
    def elapsed_ms(self) -> int: ...
    @property
    def places(self) -> int: ...
    @property
    def transitions(self) -> int: ...
    @property
    def invariants_found(self) -> int: ...
    @property
    def structural_result(self) -> str: ...
    def is_proven(self) -> bool: ...
    def is_violated(self) -> bool: ...

class PropertyResult:
    # `property` as a getter name shadows the `@property` decorator within the
    # class body, so use the fully qualified `@builtins.property` here.
    @builtins.property
    def property(self) -> SmtProperty: ...
    @builtins.property
    def result(self) -> VerificationResult: ...

class SubnetVerificationResult:
    def synthetic_net(self) -> Net: ...
    def property_results(self) -> list[PropertyResult]: ...
    def all_proven(self) -> bool: ...
    def any_violated(self) -> bool: ...

class VerificationHarness:
    def __init__(self) -> None: ...
    def input(
        self, port_name: str, supplier: Callable[[], Any]
    ) -> VerificationHarness: ...
    def property(self, property: SmtProperty) -> VerificationHarness: ...

class EnvironmentAnalysisMode:
    """Opaque VER-006 environment-injection mode; build via the constructors below."""

def always_available() -> EnvironmentAnalysisMode: ...
def bounded(max_tokens: int) -> EnvironmentAnalysisMode: ...
def ignore() -> EnvironmentAnalysisMode: ...
def deadlock_free() -> SmtProperty: ...
def terminates_at_sink() -> SmtProperty: ...
def mutual_exclusion(places: list[str]) -> SmtProperty: ...
def place_bound(place: str, bound: int) -> SmtProperty: ...
def unreachable(places: list[str]) -> SmtProperty: ...
def branch_place_bound(place: str, bound: int) -> SmtProperty: ...
def joined_or_dead_lettered(pending: str) -> SmtProperty: ...
def verify_net(
    net: Net,
    property: SmtProperty,
    *,
    initial_marking: dict[str, int] | None = ...,
    environment_places: list[str] | None = ...,
    environment_mode: EnvironmentAnalysisMode | None = ...,
    sink_places: list[str] | None = ...,
    budget_places: list[str] | None = ...,
    timeout_ms: int = ...,
    nu_max_classes: int | None = ...,
    fragment_mode: str | int | None = ...,
    carrier_places: list[str] | None = ...,
    priority_semantics: str | int | None = ...,
    certificate_check: bool = ...,
    counterexample_replay: bool = ...,
    semiflow_invariants: bool = ...,
) -> VerificationResult: ...
def verify_subnet(
    subnet: SubnetDef,
    harness: VerificationHarness,
    *,
    environment_mode: EnvironmentAnalysisMode | None = ...,
) -> SubnetVerificationResult: ...
def encode_smt_scripts(
    net: Net,
    property: SmtProperty,
    *,
    initial_marking: dict[str, int] | None = ...,
    environment_places: list[str] | None = ...,
    environment_mode: EnvironmentAnalysisMode | None = ...,
    sink_places: list[str] | None = ...,
    budget_places: list[str] | None = ...,
    fragment_mode: str | int | None = ...,
    carrier_places: list[str] | None = ...,
    counterexample_replay: bool = ...,
    semiflow_invariants: bool = ...,
) -> dict[str, str | bool | None]: ...
def z3_available() -> bool: ...

# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

class RankDir(Enum):
    TopToBottom = ...
    LeftToRight = ...
    BottomToTop = ...
    RightToLeft = ...

class DotConfig:
    direction: RankDir
    show_types: bool
    show_intervals: bool
    show_priority: bool
    environment_places: list[str]
    def __init__(
        self,
        direction: RankDir = ...,
        show_types: bool = ...,
        show_intervals: bool = ...,
        show_priority: bool = ...,
        environment_places: list[str] = ...,
    ) -> None: ...

def dot_export(net: Net, config: DotConfig | None = ...) -> str: ...

# ---------------------------------------------------------------------------
# Debug (only present when HAS_DEBUG=True)
# ---------------------------------------------------------------------------

class SessionSummary:
    @property
    def session_id(self) -> str: ...
    @property
    def net_name(self) -> str: ...
    @property
    def active(self) -> bool: ...
    @property
    def event_count(self) -> int: ...
    @property
    def tags(self) -> dict[str, str]: ...
    @property
    def end_time(self) -> str | None: ...
    @property
    def duration_ms(self) -> int | None: ...

class DebugProtocolHandler:
    def __init__(self) -> None: ...
    def register_session(
        self,
        session_id: str,
        net: Net,
        tags: Mapping[str, str] | None = ...,
    ) -> None: ...
    def complete_session(self, session_id: str) -> None: ...
    def remove_session(self, session_id: str) -> None: ...
    def list_sessions(
        self,
        limit: int = ...,
        active_only: bool | None = ...,
        tag_filter: Mapping[str, str] | None = ...,
    ) -> list[SessionSummary]: ...
    def client_connected(
        self, client_id: str, callback: Callable[[str], None]
    ) -> None: ...
    def client_disconnected(self, client_id: str) -> None: ...
    def handle_command(self, client_id: str, command_json: str) -> None: ...
