"""Type stubs for libpetri.model."""

from __future__ import annotations

from typing import TypeAlias

from . import _libpetri as _ext

Place: TypeAlias = _ext.Place
InputSpec: TypeAlias = _ext.InputSpec
OutputSpec: TypeAlias = _ext.OutputSpec
InhibitorArc: TypeAlias = _ext.InhibitorArc
ReadArc: TypeAlias = _ext.ReadArc
ResetArc: TypeAlias = _ext.ResetArc
Timing: TypeAlias = _ext.Timing
TransitionContext: TypeAlias = _ext.TransitionContext

BuiltTransition: TypeAlias = _ext.Transition
TransitionBuilder: TypeAlias = _ext.TransitionBuilder
BuiltinAction: TypeAlias = _ext.BuiltinAction
fork: BuiltinAction
passthrough: BuiltinAction
BuiltNet: TypeAlias = _ext.Net
NetBuilder: TypeAlias = _ext.NetBuilder
Port: TypeAlias = _ext.Port
Channel: TypeAlias = _ext.Channel
SubnetInstance: TypeAlias = _ext.SubnetInstance
Instance: TypeAlias = _ext.Instance
BuiltSubnetDef: TypeAlias = _ext.SubnetDef
SubnetDefBuilder: TypeAlias = _ext.SubnetDefBuilder

PlaceLike: TypeAlias = str | Place
OutputLike: TypeAlias = Place | OutputSpec

def Transition(name: str) -> TransitionBuilder: ...
def Net(name: str) -> NetBuilder: ...
def SubnetDef(name: str) -> SubnetDefBuilder: ...

# Re-exports of factory functions from the extension
def one(p: Place) -> InputSpec: ...
def exactly(count: int, p: Place) -> InputSpec: ...
def all_tokens(p: Place) -> InputSpec: ...
def at_least(min: int, p: Place) -> InputSpec: ...
def out_place(p: Place) -> OutputSpec: ...

out = out_place

def forward_input(from_: Place, to: Place) -> OutputSpec: ...
def inhibitor(p: Place) -> InhibitorArc: ...
def read(p: Place) -> ReadArc: ...
def reset(p: Place) -> ResetArc: ...
def immediate() -> Timing: ...
def deadline(by_ms: int) -> Timing: ...
def delayed(after_ms: int) -> Timing: ...
def window(earliest_ms: int, latest_ms: int) -> Timing: ...
def exact(at_ms: int) -> Timing:
    """Exact timing, interval ``[at_ms, at_ms]``.

    Precise for verification/simulation; under wall-clock execution it is enforced *softly* — the
    transition fires at the first opportunity at or after ``at_ms`` and is never force-disabled for
    being observed late (TIME-006). Prefer :func:`delayed` for a plain lower bound, or
    :func:`window` for a hard bounded window.
    """
    ...
def and_(*children: OutputLike) -> OutputSpec: ...
def and_outputs(*children: OutputLike) -> OutputSpec: ...
def xor(*children: OutputLike) -> OutputSpec: ...
def xor_outputs(*children: OutputLike) -> OutputSpec: ...
def timeout(after_ms: int, child: OutputLike) -> OutputSpec: ...
