"""Type stubs for libpetri.runtime."""

from __future__ import annotations

from collections.abc import Awaitable, Iterable, Iterator, Mapping
from dataclasses import dataclass
from typing import Any

from . import _libpetri as _ext
from .model import BuiltNet, PlaceLike

class MarkingView(Mapping[str, tuple[Any, ...]]):
    def __init__(
        self, data: Mapping[str, Iterable[Any]] | MarkingView | None = ...
    ) -> None: ...
    @classmethod
    def from_snapshot(
        cls, data: Mapping[str, Iterable[Mapping[str, Any]]]
    ) -> MarkingView: ...
    def __getitem__(self, place_name: str) -> tuple[Any, ...]: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def places(self) -> tuple[str, ...]: ...
    def tokens(self, place: PlaceLike) -> tuple[Any, ...]: ...
    def timestamps(self, place: PlaceLike) -> tuple[int, ...]: ...
    def count(self, place: PlaceLike) -> int: ...
    def has_tokens(self, place: PlaceLike) -> bool: ...
    def first(self, place: PlaceLike, default: Any = ...) -> Any: ...
    def to_dict(self) -> dict[str, list[Any]]: ...
    def snapshot(self) -> dict[str, list[dict[str, Any]]]: ...

@dataclass(slots=True, frozen=True)
class ExecutorOptions:
    environment_places: tuple[PlaceLike, ...] = ...
    skip_output_validation: bool = ...
    def native(self) -> _ext.ExecutorOptions: ...

class CompiledNet:
    def __init__(self, target: BuiltNet | _ext.CompiledNet) -> None: ...
    @property
    def name(self) -> str: ...
    def run_sync(
        self,
        *,
        initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
        options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
        event_store: _ext.InMemoryEventStore | None = ...,
    ) -> MarkingView: ...
    def start_async(
        self,
        *,
        initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
        options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
        event_store: _ext.InMemoryEventStore | None = ...,
    ) -> tuple[ExecutorHandle, Awaitable[MarkingView]]: ...
    async def run_async(
        self,
        *,
        initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
        options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
        event_store: _ext.InMemoryEventStore | None = ...,
    ) -> MarkingView: ...

class ExecutorHandle:
    def __init__(self, inner: _ext.ExecutorHandle) -> None: ...
    def inject(self, place: PlaceLike, value: Any) -> bool: ...
    def drain(self) -> bool: ...
    def close(self) -> bool: ...
    @property
    def drained(self) -> bool: ...
    async def snapshot(self) -> MarkingView: ...

ExecutionTarget = BuiltNet | CompiledNet | _ext.CompiledNet

def compile(net: BuiltNet) -> CompiledNet: ...
def run_sync(
    target: ExecutionTarget,
    *,
    initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
    options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
    event_store: _ext.InMemoryEventStore | None = ...,
) -> MarkingView: ...
def start_async(
    target: ExecutionTarget,
    *,
    initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
    options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
    event_store: _ext.InMemoryEventStore | None = ...,
) -> tuple[ExecutorHandle, Awaitable[MarkingView]]: ...
async def run_async(
    target: ExecutionTarget,
    *,
    initial: Mapping[PlaceLike, Iterable[Any]] | MarkingView | None = ...,
    options: ExecutorOptions | _ext.ExecutorOptions | None = ...,
    event_store: _ext.InMemoryEventStore | None = ...,
) -> MarkingView: ...
