package org.libpetri.smt.z3;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.libpetri.analysis.EnvironmentAnalysisMode;
import org.libpetri.analysis.FragmentMode;
import org.libpetri.analysis.MarkingState;
import org.libpetri.analysis.NameFragment;
import org.libpetri.core.Arc.In;
import org.libpetri.core.Arc.Out;
import org.libpetri.core.MatchSpec;
import org.libpetri.core.NameId;
import org.libpetri.core.PetriNet;
import org.libpetri.core.Place;
import org.libpetri.core.Transition;
import org.libpetri.smt.SmtProperty;
import org.libpetri.smt.SmtVerifier;
import org.libpetri.smt.encoding.FlatNet;
import org.libpetri.smt.encoding.FlatTransition;
import org.libpetri.smt.encoding.NetFlattener;
import org.libpetri.smt.z3.SlotBoundLp.LpAnswer;
import org.libpetri.smt.z3.SlotBoundLp.ScaledCover;
import org.libpetri.smt.z3.SlotBoundLp.SlotBound;
import org.libpetri.smt.z3.SlotLpFixtures.Row;

import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Function;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Differential tests of the colour-slot linear program of [NU-053] ({@link SlotBoundLp}):
 * against the state space, against the semiflow bound it replaced, against z3 as an independent
 * optimiser, and through {@code buildPlan} with deliberately wrong answers, which the exact
 * re-check must refuse.
 *
 * <p>The corpus is the shared parity cases ({@code spec/verification-fixtures/slot-bound-lp.json})
 * and seeded random small &nu;-nets, generated by the same generator and seeds as the Rust suite
 * ({@code rust/libpetri-verification/tests/slot_bound_lp.rs}). The Rust corpus also holds the
 * PNID relay nets of [NU-054]; the relay goldens pin their {@code k} here through the script
 * parity test.
 */
class SlotBoundLpDifferentialTest {

    static boolean z3Available() {
        return SmtVerifier.z3Available();
    }

    /** One LP subject: a flat net, its initial marking and its coloured places. */
    record Subject(String id, FlatNet flat, MarkingState initial, int[] coloured) {}

    private static List<Subject> paritySubjects() {
        return SlotLpFixtures.parityCases().stream()
            .map(c -> new Subject(c.id(), c.flat(), c.initial(), c.coloured())).toList();
    }

    /** xorshift64*, as in the Rust suite, so both languages draw the same nets. */
    private static final class Rng {
        private long state;

        Rng(long state) {
            this.state = state;
        }

        long next() {
            state ^= state >>> 12;
            state ^= state << 25;
            state ^= state >>> 27;
            return state * 0x2545_F491_4F6C_DD1DL;
        }

        int below(long n) {
            return (int) Long.remainderUnsigned(next(), n);
        }

        boolean chance(long percent) {
            return below(100) < percent;
        }
    }

    /**
     * A seeded small &nu;-like flat net: two keys (sometimes a third coloured carrier), a budget,
     * a few uncoloured places, mints into the keys, joins out of them, a coloured drain now and
     * then, and uncoloured rows, some with a reset or consume-all arc on an uncoloured place.
     * Coloured places start empty.
     */
    static Subject randomSubject(long seed) {
        var rng = new Rng((seed * 0x9E37_79B9_7F4A_7C15L) | 1);
        boolean carrier = rng.chance(30);
        int extra = 1 + rng.below(3);
        var names = new ArrayList<>(List.of("a", "b", "budget"));
        if (carrier) {
            names.add("c");
        }
        for (int i = 0; i < extra; i++) {
            names.add("u" + i);
        }
        names.sort(null);
        int n = names.size();
        Function<String, Integer> idx = names::indexOf;
        int[] keys = carrier ? new int[] {idx.apply("a"), idx.apply("b"), idx.apply("c")}
            : new int[] {idx.apply("a"), idx.apply("b")};
        int carrierPlace = carrier ? idx.apply("c") : -1;
        var unc = new ArrayList<Integer>();
        for (int p = 0; p < n; p++) {
            final int q = p;
            if (Arrays.stream(keys).noneMatch(k -> k == q)) {
                unc.add(p);
            }
        }
        var rows = new ArrayList<Row>();
        int budget = idx.apply("budget");
        int mints = 1 + rng.below(2);
        for (int m = 0; m < mints; m++) {
            int[] pre = new int[n];
            int[] post = new int[n];
            pre[budget] = 1 + rng.below(3);
            if (rng.chance(30)) {
                pre[unc.get(rng.below(unc.size()))] += 1;
            }
            for (int k : keys) {
                if (rng.chance(85) || k == idx.apply("a")) {
                    post[k] = 1;
                }
            }
            if (rng.chance(30)) {
                post[unc.get(rng.below(unc.size()))] += 1;
            }
            rows.add(row(names, "mint" + m, pre, post, List.of(), List.of()));
        }
        int joins = 1 + rng.below(2);
        for (int j = 0; j < joins; j++) {
            int[] pre = new int[n];
            int[] post = new int[n];
            for (int k : keys) {
                if (k != carrierPlace || rng.chance(50)) {
                    pre[k] = 1;
                }
            }
            post[budget] = rng.below(3);
            if (rng.chance(50)) {
                post[unc.get(rng.below(unc.size()))] += 1;
            }
            rows.add(row(names, "join" + j, pre, post, List.of(), List.of()));
        }
        if (rng.chance(30)) {
            int[] pre = new int[n];
            int[] post = new int[n];
            pre[keys[rng.below(keys.length)]] = 1;
            post[unc.get(rng.below(unc.size()))] = 1;
            rows.add(row(names, "drain", pre, post, List.of(), List.of()));
        }
        int sides = rng.below(4);
        for (int t = 0; t < sides; t++) {
            int[] pre = new int[n];
            int[] post = new int[n];
            int from = unc.get(rng.below(unc.size()));
            int to = unc.get(rng.below(unc.size()));
            pre[from] = 1 + rng.below(2);
            post[to] += 1 + rng.below(2);
            var reset = new ArrayList<Integer>();
            var all = new ArrayList<Integer>();
            int side = unc.get(rng.below(unc.size()));
            int choice = rng.below(6);
            if (choice == 0 && side != from) {
                reset.add(side);
            } else if (choice == 1) {
                pre[from] = 1;
                all.add(from);
            }
            rows.add(row(names, "side" + t, pre, post, reset, all));
        }
        var tokens = new LinkedHashMap<String, Integer>();
        tokens.put("budget", rng.below(4));
        for (int u : unc) {
            if (!names.get(u).equals("budget") && rng.chance(40)) {
                tokens.put(names.get(u), 1 + rng.below(2));
            }
        }
        FlatNet flat = SlotLpFixtures.flat(names, rows);
        return new Subject("random-" + seed, flat, SlotLpFixtures.marking(flat, tokens), keys.clone());
    }

    private static Row row(List<String> names, String name, int[] pre, int[] post, List<Integer> reset,
                           List<Integer> all) {
        Map<String, Integer> preM = new LinkedHashMap<>();
        Map<String, Integer> postM = new LinkedHashMap<>();
        for (int p = 0; p < names.size(); p++) {
            if (pre[p] != 0) {
                preM.put(names.get(p), pre[p]);
            }
            if (post[p] != 0) {
                postM.put(names.get(p), post[p]);
            }
        }
        Set<String> resetS = new HashSet<>();
        reset.forEach(p -> resetS.add(names.get(p)));
        Set<String> allS = new HashSet<>();
        all.forEach(p -> allS.add(names.get(p)));
        return new Row(name, preM, postM, resetS, allS);
    }

    private static List<Subject> corpus() {
        var all = new ArrayList<>(paritySubjects());
        for (long seed = 0; seed < 300; seed++) {
            all.add(randomSubject(seed));
        }
        return all;
    }

    private static SlotBound lpBound(Subject s) {
        return SlotBoundLp.checked(s.flat(), s.initial(), s.coloured(),
            SlotBoundLp.solve(s.flat(), s.initial(), s.coloured()));
    }

    private static long[] m0(Subject s) {
        long[] m = new long[s.flat().placeCount()];
        for (int p = 0; p < m.length; p++) {
            m[p] = s.initial().tokens(s.flat().places().get(p));
        }
        return m;
    }

    private static boolean isColoured(Subject s, int p) {
        return Arrays.stream(s.coloured()).anyMatch(c -> c == p);
    }

    private static boolean clears(FlatTransition t, int p) {
        return t.consumeAll()[p] || Arrays.stream(t.resetPlaces()).anyMatch(r -> r == p);
    }

    // ---- explicit state spaces ----

    private static final int STATE_CAP = 20_000;

    /**
     * Fires a row as Lean {@code fireAD} does: a reset or consume-all place ends at the row's
     * deposit, every other place at {@code m - pre + post}. Inhibitor and read arcs are ignored,
     * which only adds markings.
     */
    private static long[] fireAD(FlatTransition t, long[] m) {
        for (int p = 0; p < m.length; p++) {
            if (t.preVector()[p] > m[p]) {
                return null;
            }
        }
        long[] out = new long[m.length];
        for (int p = 0; p < m.length; p++) {
            out[p] = clears(t, p) ? t.postVector()[p] : m[p] - t.preVector()[p] + t.postVector()[p];
        }
        return out;
    }

    private record Max(long value, boolean closed) {}

    /** The largest coloured token count over the {@code fireAD} state space, and whether it closed. */
    private static Max maxColouredTokens(Subject s) {
        long[] start = m0(s);
        var seen = new HashSet<List<Long>>();
        seen.add(boxed(start));
        var queue = new ArrayDeque<long[]>();
        queue.add(start);
        long best = 0;
        while (!queue.isEmpty()) {
            long[] m = queue.poll();
            long sum = 0;
            for (int p : s.coloured()) {
                sum += m[p];
            }
            best = Math.max(best, sum);
            for (FlatTransition t : s.flat().transitions()) {
                long[] next = fireAD(t, m);
                if (next != null) {
                    if (seen.size() >= STATE_CAP) {
                        return new Max(best, false);
                    }
                    if (seen.add(boxed(next))) {
                        queue.add(next);
                    }
                }
            }
        }
        return new Max(best, true);
    }

    private static List<Long> boxed(long[] m) {
        return Arrays.stream(m).boxed().toList();
    }

    /** A name-semantics state: uncoloured counts, and the coloured tokens as sorted (place, name) pairs. */
    private record NameState(List<Long> unc, List<Long> col) {}

    private static long pair(int place, long name) {
        return ((long) place << 32) | name;
    }

    /** Names renamed by first appearance, so the space stays finite. */
    private static NameState normal(List<Long> unc, List<Long> col) {
        var sorted = new ArrayList<>(col);
        sorted.sort(null);
        var map = new HashMap<Long, Long>();
        var renamed = new ArrayList<Long>(sorted.size());
        for (long e : sorted) {
            long name = e & 0xFFFF_FFFFL;
            long next = map.size();
            long to = map.computeIfAbsent(name, _ -> next);
            renamed.add(pair((int) (e >>> 32), to));
        }
        renamed.sort(null);
        return new NameState(unc, List.copyOf(renamed));
    }

    private record Live(long names, long tokens, boolean closed) {}

    /**
     * The name semantics of the flat rows: a row consuming coloured places takes one name from
     * all of them and writes it into its coloured outputs; a row writing coloured places without
     * consuming one writes a fresh name. The largest number of names live at once and the largest
     * coloured token count, and whether the space closed.
     */
    private static Live maxLiveNames(Subject s) {
        int n = s.flat().placeCount();
        var start = normal(boxed(m0(s)), List.of());
        var seen = new HashSet<NameState>();
        seen.add(start);
        var queue = new ArrayDeque<NameState>();
        queue.add(start);
        long live = 0;
        long tokens = 0;
        while (!queue.isEmpty()) {
            var st = queue.poll();
            var names = new TreeSet<Long>();
            for (long e : st.col()) {
                names.add(e & 0xFFFF_FFFFL);
            }
            live = Math.max(live, names.size());
            tokens = Math.max(tokens, st.col().size());
            for (FlatTransition t : s.flat().transitions()) {
                boolean uncOk = true;
                for (int p = 0; p < n; p++) {
                    if (!isColoured(s, p) && t.preVector()[p] > st.unc().get(p)) {
                        uncOk = false;
                    }
                }
                if (!uncOk) {
                    continue;
                }
                var firedUnc = new ArrayList<Long>(n);
                for (int p = 0; p < n; p++) {
                    if (isColoured(s, p)) {
                        firedUnc.add(0L);
                    } else if (clears(t, p)) {
                        firedUnc.add((long) t.postVector()[p]);
                    } else {
                        firedUnc.add(st.unc().get(p) - t.preVector()[p] + t.postVector()[p]);
                    }
                }
                var colIn = Arrays.stream(s.coloured()).filter(p -> t.preVector()[p] > 0).toArray();
                var colOut = Arrays.stream(s.coloured()).filter(p -> t.postVector()[p] > 0).toArray();
                var candidates = new ArrayList<Long>();
                if (colIn.length == 0) {
                    long x = 0;
                    while (names.contains(x)) {
                        x++;
                    }
                    candidates.add(x);
                } else {
                    for (long x : names) {
                        boolean ok = true;
                        for (int p : colIn) {
                            long have = st.col().stream().filter(e -> e == pair(p, x)).count();
                            ok &= have >= t.preVector()[p];
                        }
                        if (ok) {
                            candidates.add(x);
                        }
                    }
                }
                if (colIn.length == 0 && colOut.length == 0) {
                    var next = normal(List.copyOf(firedUnc), st.col());
                    if (seen.size() >= STATE_CAP) {
                        return new Live(live, tokens, false);
                    }
                    if (seen.add(next)) {
                        queue.add(next);
                    }
                    continue;
                }
                for (long x : candidates) {
                    var c = new ArrayList<>(st.col());
                    for (int p : colIn) {
                        for (int i = 0; i < t.preVector()[p]; i++) {
                            c.remove(Long.valueOf(pair(p, x)));
                        }
                    }
                    for (int p : colOut) {
                        for (int i = 0; i < t.postVector()[p]; i++) {
                            c.add(pair(p, x));
                        }
                    }
                    var next = normal(List.copyOf(firedUnc), c);
                    if (seen.size() >= STATE_CAP) {
                        return new Live(live, tokens, false);
                    }
                    if (seen.add(next)) {
                        queue.add(next);
                    }
                }
            }
        }
        return new Live(live, tokens, true);
    }

    /**
     * LP {@code k} &ge; the largest coloured token count &ge; the largest number of live names, on
     * every subject with an optimum; the state space may be cut at {@link #STATE_CAP}, and every
     * marking it holds is reachable.
     */
    @Test
    void lpKBoundsTheExplicitStateSpace() {
        int checked = 0;
        int tight = 0;
        for (var s : corpus()) {
            if (!(lpBound(s) instanceof SlotBound.Bound(int k, var _, var _, var _))) {
                continue;
            }
            var tokens = maxColouredTokens(s);
            var names = maxLiveNames(s);
            assertTrue(tokens.value() <= k, "[" + s.id() + "] " + tokens.value() + " coloured tokens reachable above k=" + k);
            assertTrue(names.names() <= names.tokens(), "[" + s.id() + "]");
            if (tokens.closed() && names.closed()) {
                assertTrue(names.tokens() <= tokens.value(), "[" + s.id() + "] name semantics beyond fireAD");
            }
            checked++;
            if (tokens.value() == k) {
                tight++;
            }
        }
        System.out.println("[slot-bound LP] k bounds the state space on " + checked + " subjects, tight on " + tight);
        assertTrue(checked >= 200 && tight >= 100, "checked " + checked + ", tight " + tight);
    }

    /**
     * LP {@code k} &le; the semiflow bound wherever the semiflow code returned one (truncated or
     * not), and an infeasible program means the semiflow code returned none: every covering
     * semiflow, and the summed fallback, is a feasible weighting.
     */
    @Test
    void lpKNeverExceedsTheSemiflowBound() {
        int compared = 0;
        int smaller = 0;
        int admitted = 0;
        for (var s : corpus()) {
            Integer old = OldSlotBound.colourSlotBound(s.coloured(), OldSlotBound.validatedSemiflows(s.flat(), s.initial()));
            switch (lpBound(s)) {
                case SlotBound.Bound b when old != null -> {
                    assertTrue(b.k() <= old, "[" + s.id() + "] LP k=" + b.k() + " above the semiflow bound " + old);
                    compared++;
                    if (b.k() < old) {
                        smaller++;
                    }
                }
                case SlotBound.Bound b -> admitted++;
                case SlotBound.Infeasible i ->
                    assertNull(old, "[" + s.id() + "] LP infeasible but a covering semiflow exists");
                case SlotBound other -> fail("[" + s.id() + "] unexpected answer " + other);
            }
        }
        System.out.println("[slot-bound LP] compared " + compared + " (LP smaller on " + smaller + "); "
            + admitted + " admitted that the semiflows refused");
        // The Rust suite asks for 40 compared subjects; its corpus adds the PNID relay nets, which
        // this one leaves out. Parity cases and random nets alone compare 35.
        assertTrue(compared >= 30 && smaller >= 10 && admitted >= 10, compared + " " + smaller + " " + admitted);
    }

    /** A {@code QF_LRA} question about the program: {@code extra} conjoined to its constraints. */
    private static String lraScript(Subject s, String extra) {
        int n = s.flat().placeCount();
        var out = new StringBuilder("(set-logic QF_LRA)\n");
        for (int p = 0; p < n; p++) {
            out.append("(declare-const y").append(p).append(" Real)\n(assert (>= y").append(p).append(" 0.0))\n");
        }
        for (int p : s.coloured()) {
            out.append("(assert (>= y").append(p).append(" 1.0))\n");
        }
        for (FlatTransition t : s.flat().transitions()) {
            var terms = new ArrayList<String>();
            for (int p = 0; p < n; p++) {
                long v = (long) t.postVector()[p] - t.preVector()[p];
                if (v != 0) {
                    terms.add("(* " + real(v) + " y" + p + ")");
                }
            }
            out.append("(assert (<= ").append(sum(terms)).append(" 0.0))\n");
        }
        long[] m0 = m0(s);
        var objective = new ArrayList<String>();
        for (int p = 0; p < n; p++) {
            if (m0[p] != 0) {
                objective.add("(* " + real(m0[p]) + " y" + p + ")");
            }
        }
        out.append(extra.replace("OBJ", sum(objective)));
        out.append("\n(check-sat)\n");
        return out.toString();
    }

    private static String real(long v) {
        return v < 0 ? "(- " + (-v) + ".0)" : v + ".0";
    }

    private static String sum(List<String> terms) {
        return terms.isEmpty() ? "0.0" : "(+ 0.0 " + String.join(" ", terms) + ")";
    }

    private static String z3Answer(String script) throws IOException, InterruptedException {
        String program = System.getenv("LIBPETRI_Z3");
        if (program == null || program.isEmpty()) {
            program = "z3";
        }
        var proc = new ProcessBuilder(program, "-smt2", "-in", "-T:60").redirectErrorStream(true).start();
        try (var in = proc.getOutputStream()) {
            in.write(script.getBytes(StandardCharsets.UTF_8));
        }
        String out = new String(proc.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        proc.waitFor();
        return out.lines().findFirst().orElse("").trim();
    }

    /**
     * The optimum agrees with z3 over the reals: at the LP's optimum the program is satisfiable,
     * strictly below it unsatisfiable, and an infeasible program is unsatisfiable outright.
     */
    @Test
    @EnabledIf("z3Available")
    void theLpOptimumAgreesWithZ3() throws Exception {
        int agreed = 0;
        for (var s : corpus()) {
            switch (lpBound(s)) {
                case SlotBound.Bound b -> {
                    String v = "(/ " + b.value().numerator() + ".0 " + b.value().denominator() + ".0)";
                    assertEquals("sat", z3Answer(lraScript(s, "(assert (<= OBJ " + v + "))")), "[" + s.id() + "]");
                    assertEquals("unsat", z3Answer(lraScript(s, "(assert (< OBJ " + v + "))")),
                        "[" + s.id() + "] " + b.value());
                }
                case SlotBound.Infeasible i -> assertEquals("unsat", z3Answer(lraScript(s, "")), "[" + s.id() + "]");
                case SlotBound other -> fail("[" + s.id() + "] unexpected answer " + other);
            }
            agreed++;
        }
        System.out.println("[slot-bound LP] z3 agrees on " + agreed + " subjects");
    }

    // ---- the re-check cannot be bypassed ----

    private static final Place<Integer> SOURCE = Place.of("source", Integer.class);
    private static final Place<Integer> BUDGET = Place.of("budget", Integer.class);
    private static final Place<Integer> PENDING = Place.of("pending", Integer.class);
    private static final Place<String> BRANCH_A = Place.of("branchA", String.class);
    private static final Place<String> BRANCH_B = Place.of("branchB", String.class);
    private static final Place<String> MERGED = Place.of("merged", String.class);
    private static final Place<String> ARCHIVED = Place.of("archived", String.class);

    /** The scatter-gather &nu;-net, with {@code archive: merged -> archived} when asked. */
    private static PetriNet scatterGather(boolean archive) {
        var fork = Transition.builder("fork")
            .inputs(In.one(SOURCE), In.one(BUDGET))
            .outputs(Out.and(BRANCH_A, BRANCH_B, PENDING))
            .build();
        var join = Transition.builder("join")
            .inputs(In.one(BRANCH_A), In.one(BRANCH_B), In.one(PENDING))
            .match(MatchSpec.builder()
                .key(BRANCH_A, (String s) -> NameId.of(s))
                .key(BRANCH_B, (String s) -> NameId.of(s))
                .build())
            .outputs(Out.and(MERGED, BUDGET))
            .build();
        var b = PetriNet.builder(archive ? "scatter_gather_archive" : "scatter_gather").transitions(fork, join);
        if (archive) {
            b.transition(Transition.builder("archive").inputs(In.one(MERGED)).outputs(Out.place(ARCHIVED)).build());
        }
        return b.build();
    }

    private static MarkingState scatterGatherMarking() {
        return MarkingState.builder().tokens(SOURCE, 3).tokens(BUDGET, 2).build();
    }

    private record Planned(NameColouredEncoder.ColouredPlan plan, SlotBound reported, FlatNet flat) {}

    /** {@code buildPlan} with the simplex replaced by {@code answer}, and the bound it reported. */
    private static Planned planWith(PetriNet net, MarkingState initial, Function<FlatNet, LpAnswer> answer) {
        var flat = NetFlattener.flatten(net, Set.of(), EnvironmentAnalysisMode.ignore());
        var mints = NameFragment.declaredMints(net, Set.of("budget"), Set.of());
        var reported = new SlotBound[1];
        var plan = NameColouredEncoder.buildPlan(net, flat, initial, mints, FragmentMode.BASE, Set.of(),
            _ -> answer.apply(flat), b -> reported[0] = b);
        assertNotNull(reported[0], "the sink is called once the plan reaches the bound");
        return new Planned(plan, reported[0], flat);
    }

    /** Weights by place name, every other place 0. */
    private static LpAnswer weights(FlatNet flat, Map<String, Long> byName, long d) {
        var w = new ArrayList<BigInteger>();
        for (int p = 0; p < flat.placeCount(); p++) {
            w.add(BigInteger.valueOf(byName.getOrDefault(flat.places().get(p).name(), 0L)));
        }
        return new LpAnswer.Optimal(new ScaledCover(w, BigInteger.valueOf(d)), 5, 2);
    }

    private static Map<String, Long> w(Object... pairs) {
        var m = new LinkedHashMap<String, Long>();
        for (int i = 0; i < pairs.length; i += 2) {
            m.put((String) pairs[i], ((Number) pairs[i + 1]).longValue());
        }
        return m;
    }

    @Test
    void buildPlanTakesKOnlyFromAWeightingTheReCheckAccepts() {
        var net = scatterGather(true);
        var m0 = scatterGatherMarking();

        var lp = planWith(net, m0, flat -> SlotBoundLp.solve(flat, m0, SlotLpFixtures.indices(flat, "branchA", "branchB")));
        assertNotNull(lp.plan(), String.valueOf(lp.reported()));
        assertEquals(4, lp.plan().k());

        record Refused(Map<String, Long> weights, long d, String reason) {}
        var optimal = w("branchA", 1, "branchB", 1, "budget", 2);
        var withArchived = new LinkedHashMap<>(optimal);
        withArchived.put("archived", 1L);
        for (var r : List.of(
                new Refused(w("branchA", 1, "branchB", 1, "budget", 2, "pending", -1), 1,
                    "place 'pending' has negative weight -1"),
                new Refused(w("branchA", 2, "branchB", 1, "budget", 6), 2,
                    "coloured place 'branchB' has weight 1 below the denominator 2"),
                new Refused(withArchived, 1, "transition 'archive' increases the weighted sum by 1"),
                new Refused(optimal, 0, "denominator 0 is not positive"),
                new Refused(optimal, -1, "denominator -1 is not positive"),
                new Refused(w("branchA", 1, "branchB", 1, "budget", 2, "source", 1L << 31), 1,
                    "k=6442450948 exceeds 2147483647"))) {
            var p = planWith(net, m0, flat -> weights(flat, r.weights(), r.d()));
            assertNull(p.plan(), r.reason());
            assertEquals(new SlotBound.CheckFailed(r.reason()), p.reported());
            assertEquals("  Colour-slot bound: none (LP weighting failed the exact re-check: " + r.reason() + ")",
                p.reported().reportLine());
        }

        // A feasible weighting that is not optimal is accepted, with its larger k.
        var loose = planWith(net, m0, flat -> weights(flat, w("branchA", 1, "branchB", 1, "budget", 2, "source", 1), 1));
        assertNotNull(loose.plan(), String.valueOf(loose.reported()));
        assertEquals(7, loose.plan().k());
        // Every answer without a weighting refuses the plan.
        for (var answer : List.<LpAnswer>of(new LpAnswer.Infeasible(5, 2), new LpAnswer.PivotLimit(350),
                new LpAnswer.Stopped())) {
            assertNull(planWith(net, m0, _ -> answer).plan(), String.valueOf(answer));
        }
    }

    // ---- verdict invariance ----

    /** Runs a HORN script: {@code sat} proves the property, {@code unsat} violates it. */
    private static String spacer(String script) throws Exception {
        var reply = Z3Solver.resolve().run(script, "slot-bound-lp-test", Duration.ofSeconds(20), List.of());
        return reply.stdout().lines().findFirst().orElse("").trim();
    }

    /**
     * On the scatter-gather fixture (the shared coloured net whose {@code k} changed, 10 to 4), the
     * coloured encoding answers every query the same with the LP's {@code k} as with the old
     * semiflow weighting's, fed to {@code buildPlan} through its {@code lp} function. Spacer may
     * run out of time on the larger encoding ({@code unknown}); it must never answer the other way.
     */
    @Test
    @EnabledIf("z3Available")
    void theLpKAndTheSemiflowKGiveTheSameVerdicts() throws Exception {
        var net = scatterGather(false);
        var m0 = scatterGatherMarking();
        var flat = NetFlattener.flatten(net, Set.of(), EnvironmentAnalysisMode.ignore());
        int[] coloured = SlotLpFixtures.indices(flat, "branchA", "branchB");
        long[] old = OldSlotBound.colourSlotWeighting(flat.placeCount(), coloured,
            OldSlotBound.validatedSemiflows(flat, m0));
        assertNotNull(old, "the scatter-gather net has a covering semiflow");
        var oldAnswer = new LpAnswer.Optimal(new ScaledCover(
            Arrays.stream(old).mapToObj(BigInteger::valueOf).toList(), BigInteger.ONE), 0, 0);
        var oldPlan = planWith(net, m0, _ -> oldAnswer).plan();
        var lpPlan = planWith(net, m0, f -> SlotBoundLp.solve(f, m0, coloured)).plan();
        assertNotNull(oldPlan, "old plan");
        assertNotNull(lpPlan, "LP plan");
        assertEquals(List.of(10, 4), List.of(oldPlan.k(), lpPlan.k()));
        record Query(SmtProperty property, String expected) {}
        int decided = 0;
        for (var query : List.of(
                new Query(SmtProperty.placeBound(BUDGET, 2), "sat"),
                new Query(SmtProperty.placeBound(BRANCH_A, 2), "sat"),
                new Query(SmtProperty.placeBound(BRANCH_A, 1), "unsat"),
                new Query(SmtProperty.placeBound(MERGED, 2), "unsat"),
                new Query(SmtProperty.placeBound(PENDING, 2), "sat"))) {
            var answers = new ArrayList<String>();
            for (var plan : List.of(oldPlan, lpPlan)) {
                var enc = NameColouredEncoder.encode(plan, flat, m0, query.property(), List.of(), Set.of());
                assertNotNull(enc, "encodes");
                long start = System.nanoTime();
                answers.add(spacer(enc.smt2()));
                System.out.println("[slot-bound LP] k=" + plan.k() + " " + query.property() + ": "
                    + answers.getLast() + " in " + (System.nanoTime() - start) / 1_000_000 + " ms");
            }
            assertEquals(query.expected(), answers.get(1), "LP k: " + query.property());
            assertTrue(answers.get(0).equals(query.expected()) || answers.get(0).equals("unknown"),
                "old k: " + query.property() + " " + answers);
            if (answers.get(0).equals(query.expected())) {
                decided++;
            }
        }
        assertTrue(decided >= 3, "the old k decided only " + decided + " queries");
    }

    /**
     * The generator draws the Rust suite's numbers, so the two corpora are the same nets. The
     * expected values are xorshift64* in unsigned 64-bit arithmetic, as Rust computes it.
     */
    @Test
    void theRandomGeneratorDrawsTheRustSuitesNumbers() {
        record Draws(long seed, List<String> values) {}
        for (var d : List.of(
                new Draws(0, List.of("5180492295206395165", "12380297144915551517", "13389498078930870103",
                    "5599127315341312413")),
                new Draws(7, List.of("7430617906488651703", "7486449783762807604", "10902827877105278336",
                    "1178274461110533083")),
                new Draws(299, List.of("11323342715831148525", "2796339441437796201", "7758302561615449610",
                    "5782949624658342942")))) {
            var rng = new Rng((d.seed() * 0x9E37_79B9_7F4A_7C15L) | 1);
            var got = new ArrayList<String>();
            for (int i = 0; i < 4; i++) {
                got.add(Long.toUnsignedString(rng.next()));
            }
            assertEquals(d.values(), got, "seed " + d.seed());
        }
        var rng = new Rng((7 * 0x9E37_79B9_7F4A_7C15L) | 1);
        assertEquals(List.of(3, 4, 36, 83), List.of(rng.below(100), rng.below(100), rng.below(100), rng.below(100)));
    }
}
