#!/usr/bin/env python3
"""Lean <-> Rust fidelity check.

The Lean development in lean/ models specific shipped Rust functions by name
(see lean/README.md, "Fidelity"). Nothing used to fail when one of those
functions changed. This script closes that gap:

  * lean/fidelity.toml  — hand-maintained pin manifest: one [[pin]] per
                          modeled Rust item (file, fn, lean modules).
  * lean/fidelity.lock  — generated: SHA-256 of each pinned item's current
                          source span (doc comments and attributes included —
                          deliberately strict, a comment edit also trips it).

Default mode re-hashes every pinned item and compares against the lock: any
mismatch, missing item, or lock drift is a failure. Two citation guards run
alongside it — every `.rs` file cited in a Lean doc comment must have at least
one pin, and every `file.rs:NNN` line *hint* written next to a pinned item's
name must fall inside that item. The recovery workflow is printed on failure.

    python3 scripts/lean-fidelity-check.py            # verify (CI mode)
    python3 scripts/lean-fidelity-check.py --update   # regenerate the lock

stdlib only (tomllib needs python >= 3.11). Exit codes: 0 clean, 1 findings,
2 usage/manifest error.
"""

from __future__ import annotations

import hashlib
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "lean" / "fidelity.toml"
LOCK = REPO_ROOT / "lean" / "fidelity.lock"
LOCK_HEADER = (
    "# lean/fidelity.lock — generated by scripts/lean-fidelity-check.py --update."
    " Do not hand-edit.\n"
)
HASH_PREFIX = 12  # hex chars shown in reports


# ---------------------------------------------------------------------------
# Rust lexing: mask comments / strings / char literals so that item search
# and brace matching only ever see real code structure.
# ---------------------------------------------------------------------------

# A char literal at position i: 'x', '\n', '\u{1F600}', ... — as opposed to a
# lifetime ('a, 'static), which has no closing quote.
_CHAR_LIT = re.compile(r"'(?:[^'\\\n]|\\(?:[^u\n]|u\{[0-9a-fA-F_]{1,6}\}))'")


def mask_rust(text: str) -> str:
    """Replace the contents of comments, strings, and char literals with
    spaces (newlines preserved), so positions are stable but delimiters
    inside them are invisible. Handles nested block comments, escaped
    strings, raw strings r#"..."#, byte/raw-byte strings, and the
    char-literal/lifetime ambiguity."""
    out = list(text)
    i, n = 0, len(text)

    def blank(a: int, b: int) -> None:
        for k in range(a, b):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if c == "/" and nxt == "/":  # line comment (incl. /// and //!)
            j = text.find("\n", i)
            j = n if j == -1 else j
            blank(i, j)
            i = j
        elif c == "/" and nxt == "*":  # block comment, nested
            depth, j = 1, i + 2
            while j < n and depth:
                if text.startswith("/*", j):
                    depth += 1
                    j += 2
                elif text.startswith("*/", j):
                    depth -= 1
                    j += 2
                else:
                    j += 1
            blank(i, j)
            i = j
        elif c in "rb" and _raw_string_at(text, i):  # r"..." / r#"..."# / br"..."
            j = _raw_string_at(text, i)
            blank(i, j)
            i = j
        elif c == "b" and nxt == '"':  # byte string
            j = _skip_quoted(text, i + 1)
            blank(i, j)
            i = j
        elif c == '"':  # string literal
            j = _skip_quoted(text, i)
            blank(i, j)
            i = j
        elif c == "'":
            m = _CHAR_LIT.match(text, i)
            if m:  # char literal
                blank(i, m.end())
                i = m.end()
            else:  # lifetime — the quote opens nothing
                i += 1
        else:
            i += 1
    return "".join(out)


def _raw_string_at(text: str, i: int) -> int:
    """If a raw (byte) string starts at i, return the index just past it,
    else 0. Shapes: r"..."  r#"..."#  br##"..."##  (any # count)."""
    j = i
    if text[j] == "b":
        j += 1
    if j >= len(text) or text[j] != "r":
        return 0
    j += 1
    hashes = 0
    while j < len(text) and text[j] == "#":
        hashes += 1
        j += 1
    if j >= len(text) or text[j] != '"':
        return 0
    close = '"' + "#" * hashes
    k = text.find(close, j + 1)
    return len(text) if k == -1 else k + len(close)


def _skip_quoted(text: str, i: int) -> int:
    """i points at the opening double quote; return index just past the
    closing quote, honoring backslash escapes."""
    j = i + 1
    n = len(text)
    while j < n:
        if text[j] == "\\":
            j += 2
        elif text[j] == '"':
            return j + 1
        else:
            j += 1
    return n


# ---------------------------------------------------------------------------
# Item location + span extraction
# ---------------------------------------------------------------------------

_VIS = r"(?:pub(?:\s*\(\s*(?:crate|super|self|in\s+[A-Za-z0-9_:]+)\s*\))?\s+)?"
_FN_QUALS = r"(?:default\s+)?(?:const\s+)?(?:async\s+)?(?:unsafe\s+)?(?:extern\s+\"[^\"]*\"\s+)?"


def _fn_pattern(name: str) -> re.Pattern:
    return re.compile(
        r"(?m)^[ \t]*" + _VIS + _FN_QUALS + r"fn\s+" + re.escape(name) + r"\b"
    )


def _type_pattern(name: str) -> re.Pattern:
    return re.compile(
        r"(?m)^[ \t]*" + _VIS + r"(?:struct|enum|union|trait)\s+" + re.escape(name) + r"\b"
    )


_IMPL_HEAD = re.compile(r"(?m)^[ \t]*(?:unsafe\s+)?impl\b")
_ATTACH = ("///", "//!", "//", "#[", "#!")  # lines pulled into the span above an item

# A top-level `#[cfg(test)] mod …`. Nothing after it is shipped code, so no pin
# may reach into it: `marking.rs` has both a `fn remove_matching` and a `#[test]
# fn remove_matching`, and hashing the test too made every unit-test edit demand
# a Lean re-verification it did not warrant.
_TEST_MOD = re.compile(r"(?m)^#\[cfg\(test\)\][ \t]*\n(?:[ \t]*\n)*[ \t]*(?:pub\s+)?mod\s+")


def _item_end(masked: str, start: int) -> int:
    """From an item head at `start`, return the index just past the item:
    the matching close brace of its body, or a top-level `;` for bodyless
    items (trait fn declarations, unit/tuple structs)."""
    depth = 0
    j = start
    n = len(masked)
    while j < n:
        c = masked[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return j + 1
        elif c == ";" and depth == 0:
            return j + 1
        j += 1
    return n


def _span_with_docs(text: str, head: int, end: int) -> tuple[int, int]:
    """Extend the span upward over contiguous doc-comment / attribute lines."""
    line_start = text.rfind("\n", 0, head) + 1
    while line_start > 0:
        prev_end = line_start - 1  # the \n
        prev_start = text.rfind("\n", 0, prev_end) + 1
        stripped = text[prev_start:prev_end].strip()
        if stripped and stripped.startswith(_ATTACH):
            line_start = prev_start
        else:
            break
    return line_start, end


def find_spans(text: str, masked: str, name: str) -> list[tuple[int, int]]:
    """All source spans in the file that define `name`: fn items, type items,
    and (for type pins) impl blocks whose header names the type. Returned in
    file order; the caller hashes their concatenation."""
    m_test = _TEST_MOD.search(masked)
    limit = m_test.start() if m_test else len(masked)
    heads: list[int] = []
    for pat in (_fn_pattern(name), _type_pattern(name)):
        heads.extend(m.start() for m in pat.finditer(masked))
    ident = re.compile(r"\b" + re.escape(name) + r"\b")
    for m in _IMPL_HEAD.finditer(masked):
        brace = masked.find("{", m.end())
        semi = masked.find(";", m.end())
        stop = min(x for x in (brace, semi, len(masked)) if x != -1)
        if ident.search(masked[m.end():stop]):
            heads.append(m.start())
    spans = []
    for head in sorted(set(heads)):
        if head >= limit:
            continue
        end = _item_end(masked, head)
        spans.append(_span_with_docs(text, head, end))
    return spans


def hash_item(path: Path, name: str) -> str | None:
    text = path.read_text(encoding="utf-8")
    spans = find_spans(text, mask_rust(text), name)
    if not spans:
        return None
    payload = b"\n".join(text[a:b].encode("utf-8") for a, b in spans)
    return hashlib.sha256(payload).hexdigest()


# ---------------------------------------------------------------------------
# Citation coverage guard
# ---------------------------------------------------------------------------

_CITATION = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_/.\-]*\.rs\b")


def lean_citations() -> list[tuple[str, str]]:
    """(cited .rs path, citing lean file) for every distinct citation."""
    lean_dir = REPO_ROOT / "lean"
    files = [lean_dir / "Libpetri.lean"] + sorted((lean_dir / "Libpetri").glob("*.lean"))
    seen: dict[str, str] = {}
    for f in files:
        for m in _CITATION.finditer(f.read_text(encoding="utf-8")):
            seen.setdefault(m.group(0), str(f.relative_to(REPO_ROOT)))
    return sorted(seen.items())


def cited_file_has_pin(cited: str, pin_files: set[str]) -> bool:
    return _resolve_cited_file(cited, pin_files) is not None


def _resolve_cited_file(cited: str, pin_files) -> str | None:
    """The pinned path a Lean citation refers to, or None when it is ambiguous
    or unpinned."""
    if cited in pin_files:
        return cited
    if "/" in cited:
        hits = [p for p in pin_files if p.endswith("/" + cited)]
    else:
        hits = [p for p in pin_files if p.rsplit("/", 1)[-1] == cited]
    return hits[0] if len(hits) == 1 else None


# ---------------------------------------------------------------------------
# Line-hint guard
# ---------------------------------------------------------------------------

# `file.rs:120` / the head of `file.rs:120-134` — the line-number *hints* in
# Lean doc comments. The item name is the primary reference and the hint is
# secondary (lean/README.md, "Fidelity"), but a hint that points into
# unrelated code is worse than no hint: it sends the next reader to the wrong
# function while the fidelity hash stays green.
_LINE_CITATION = re.compile(r"([A-Za-z0-9_][A-Za-z0-9_/.\-]*\.rs):(\d+)")

# RetrodictExec.lean deliberately cites the PRE-FIX tree (commit `1bdf586`):
# those line numbers describe code that no longer exists, so they are exempt.
HISTORICAL_CITATIONS = {"lean/Libpetri/RetrodictExec.lean"}


def _comment_blocks(src: str) -> list[tuple[int, str]]:
    """(offset, text) for every Lean comment block — `/- … -/` (nested, so
    `/--` and `/-!` are included) and each `--` line. A hint is read in the
    context of its own block: the pinned items named there are the ones it is
    allowed to point into."""
    blocks: list[tuple[int, str]] = []
    i, n = 0, len(src)
    while i < n:
        if src.startswith("/-", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if src.startswith("/-", j):
                    depth += 1
                    j += 2
                elif src.startswith("-/", j):
                    depth -= 1
                    j += 2
                else:
                    j += 1
            blocks.append((i, src[i:j]))
            i = j
        elif src.startswith("--", i):
            j = src.find("\n", i)
            j = n if j == -1 else j
            blocks.append((i, src[i:j]))
            i = j
        else:
            i += 1
    return blocks


def item_line_spans(path: Path, names: list[str]) -> dict[str, list[tuple[int, int]]]:
    """Pinned item -> its current 1-based line range(s) in `path`."""
    text = path.read_text(encoding="utf-8")
    masked = mask_rust(text)
    out: dict[str, list[tuple[int, int]]] = {}
    for name in names:
        rows = [
            (text.count("\n", 0, a) + 1, text.count("\n", 0, b) + 1)
            for a, b in find_spans(text, masked, name)
        ]
        if rows:
            out[name] = rows
    return out


def check_line_hints(pins: list[dict]) -> list[str]:
    """Every `file.rs:NNN` hint written in the same comment block as a pinned
    item's name must fall inside that item. Hints next to no pinned name (a
    struct field, a constant, a call site) are structural and skipped — the
    guard adds no manifest burden, it only stops the hints that DO name a
    pinned item from rotting silently."""
    by_file: dict[str, list[str]] = {}
    for pin in pins:
        by_file.setdefault(pin["file"], []).append(pin["fn"])
    spans = {
        f: item_line_spans(REPO_ROOT / f, fns)
        for f, fns in by_file.items()
        if (REPO_ROOT / f).exists()
    }

    problems: list[str] = []
    lean_dir = REPO_ROOT / "lean"
    files = [lean_dir / "Libpetri.lean"] + sorted((lean_dir / "Libpetri").glob("*.lean"))
    for lf in files:
        rel = str(lf.relative_to(REPO_ROOT))
        if rel in HISTORICAL_CITATIONS:
            continue
        src = lf.read_text(encoding="utf-8")
        for offset, block in _comment_blocks(src):
            # Only backticked identifiers count as naming an item: this
            # development writes every code reference as `name`, and matching
            # bare prose would flag "every disable path" as citing `disable`.
            quoted = " ".join(re.findall(r"`([^`]*)`", block))
            for m in _LINE_CITATION.finditer(block):
                cited, hint = m.group(1), int(m.group(2))
                path = _resolve_cited_file(cited, spans)
                if path is None:
                    continue
                named = {
                    name: rows
                    for name, rows in spans[path].items()
                    if re.search(r"\b" + re.escape(name) + r"\b", quoted)
                }
                if not named:
                    continue  # structural hint — nothing pinned to check it against
                if any(a <= hint <= b for rows in named.values() for a, b in rows):
                    continue
                line = src.count("\n", 0, offset + m.start()) + 1
                where = "; ".join(
                    f"{name} is at {', '.join(f'{a}-{b}' for a, b in rows)}"
                    for name, rows in sorted(named.items())
                )
                problems.append(
                    f"stale line hint: {rel}:{line} cites {cited}:{hint}, "
                    f"outside every pinned item named in that comment ({where})"
                )
    # The same hint is often repeated across a module; report each shape once.
    return sorted(dict.fromkeys(problems))


# ---------------------------------------------------------------------------
# Manifest / lock IO
# ---------------------------------------------------------------------------

def load_pins() -> list[dict]:
    try:
        manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    except FileNotFoundError:
        sys.exit(f"error: {MANIFEST.relative_to(REPO_ROOT)} not found")
    pins = manifest.get("pin", [])
    keys = set()
    for pin in pins:
        for field in ("file", "fn"):
            if field not in pin:
                sys.exit(f"error: pin missing '{field}': {pin}")
        key = f"{pin['file']}::{pin['fn']}"
        if key in keys:
            sys.exit(f"error: duplicate pin: {key}")
        keys.add(key)
    return pins


def read_lock() -> dict[str, str]:
    entries: dict[str, str] = {}
    if not LOCK.exists():
        return entries
    for line in LOCK.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, _, key = line.partition("  ")
        entries[key] = digest
    return entries


def write_lock(hashes: dict[str, str]) -> None:
    lines = [LOCK_HEADER]
    for key in sorted(hashes):
        lines.append(f"{hashes[key]}  {key}\n")
    LOCK.write_text("".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str]) -> int:
    update = "--update" in argv
    if [a for a in argv if a not in ("--update",)]:
        print(__doc__.strip().splitlines()[0])
        print("usage: lean-fidelity-check.py [--update]")
        return 2

    pins = load_pins()
    problems: list[str] = []

    # Hash every pinned item as it exists right now.
    current: dict[str, str] = {}
    for pin in pins:
        key = f"{pin['file']}::{pin['fn']}"
        path = REPO_ROOT / pin["file"]
        if not path.exists():
            problems.append(f"pinned file missing: {pin['file']}")
            continue
        digest = hash_item(path, pin["fn"])
        if digest is None:
            problems.append(f"cited function missing: {pin['fn']} ({pin['file']})")
            continue
        current[key] = digest

    # Citation coverage: every .rs file a Lean comment cites must be pinned.
    pin_files = {pin["file"] for pin in pins}
    for cited, lean_file in lean_citations():
        if not cited_file_has_pin(cited, pin_files):
            problems.append(f"citation without pin: {cited} (cited in {lean_file})")

    # Line hints next to a pinned item's name must still point at that item.
    problems.extend(check_line_hints(pins))

    if update:
        if problems:
            for p in problems:
                print(f"FAIL {p}")
            print(f"lean-fidelity: NOT updating lock ({len(problems)} problem(s))")
            return 1
        write_lock(current)
        print(f"lean-fidelity: wrote {LOCK.relative_to(REPO_ROOT)} ({len(current)} pins)")
        return 0

    # Verify against the lock.
    locked = read_lock()
    if not locked:
        problems.append("lock missing or empty — run: scripts/lean-fidelity-check.py --update")
    for pin in pins:
        key = f"{pin['file']}::{pin['fn']}"
        if key not in current:
            continue  # already reported above
        want = locked.get(key)
        if want is None:
            if locked:
                problems.append(f"lock drift: no entry for {key} — run --update after re-verifying")
        elif want != current[key]:
            leans = ", ".join(pin.get("lean", [])) or "(no lean modules listed)"
            problems.append(
                f"fidelity mismatch: {pin['fn']} ({pin['file']})\n"
                f"       expected {want[:HASH_PREFIX]}  actual {current[key][:HASH_PREFIX]}\n"
                f"       re-verify: {leans}"
            )
    for key in sorted(set(locked) - {f"{p['file']}::{p['fn']}" for p in pins}):
        problems.append(f"lock drift: stale entry {key} (pin removed?) — run --update")

    if problems:
        for p in problems:
            print(f"FAIL {p}")
        print(
            f"lean-fidelity: {len(problems)} problem(s). Workflow: open the named Rust "
            "item, re-verify the listed Lean model(s) (or add the missing pin), then "
            "run scripts/lean-fidelity-check.py --update and commit the lock."
        )
        return 1

    cited_files = {c for c, _ in lean_citations()}
    print(
        f"lean-fidelity: OK — {len(current)} pins verified, "
        f"{len(cited_files)} distinct .rs citations covered, line hints in range"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
