#!/usr/bin/env python3
"""Generate spec/coverage-matrix.md — the spec proof/test coverage matrix.

Inputs (all read-only):
  (a) spec/00-index.md              — canonical active-requirement registry
      (table rows in the "Alphabetical Cross-Reference Index" section;
      struck-through ~~ID~~ tombstones are excluded).
  (b) lean/proof-coverage.json      — hand-maintained theorem -> spec-ID
      annotations. Every `name` must exist as `theorem NAME` or `lemma NAME`
      in its claimed module under lean/, and every `id` must be an active
      spec ID; validation hard-fails otherwise.
  (c) grep of lean/**/*.lean        — spec-ID comment mentions (kept separate
      from (b): a mention is not a proof).
  (d) per-language test greps:
      java/src/test/**/*.java, typescript/tests/**/*.ts,
      rust/**/tests/**/*.rs plus rust/**/src/**/*.rs containing
      #[cfg(test)] or #![cfg(test)], python/tests/**/*.py.
      target/, node_modules/, .lake/, .venv/, dist/ are excluded.

Modes:
  (default) / --check    regenerate to memory, diff against the committed
                         file; exit 1 with a diff summary if stale
  --update               rewrite spec/coverage-matrix.md in place

python3 stdlib only.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC_INDEX = REPO / "spec" / "00-index.md"
PROOF_COVERAGE = REPO / "lean" / "proof-coverage.json"
OUTPUT = REPO / "spec" / "coverage-matrix.md"
LEAN_DIR = REPO / "lean"

# The canonical active-requirement count. spec/00-index.md is the registry;
# if the spec gains or loses a requirement, update this constant in the same
# change — the hard failure is deliberate, so index drift surfaces here.
EXPECTED_ACTIVE = 209

EXCLUDED_DIR_NAMES = {"target", "node_modules", ".lake", ".venv", "dist"}
SPEC_ID_RE = re.compile(r"\b([A-Z]{2,6}-\d{3})\b")
DECL_RE = re.compile(r"\b(?:theorem|lemma)\s+([A-Za-z_][A-Za-z0-9_'!?]*)")
RUST_CFG_TEST_RE = re.compile(r"#!?\[cfg\(test\)\]")

CHECK_MARK = "✓"
DASH = "—"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/spec-coverage-matrix.py "
    "— do not hand-edit; regenerate with --update -->"
)


def fail(msg: str) -> "NoReturn":  # noqa: F821 - py3.11 has NoReturn in typing only
    sys.stderr.write(f"spec-coverage-matrix: ERROR: {msg}\n")
    sys.exit(2)


# --------------------------------------------------------------------------
# (a) canonical active-ID list from spec/00-index.md
# --------------------------------------------------------------------------

def parse_spec_index(text: str):
    """Return (spec_files, active, tombstones).

    spec_files: list of (filename, prefix, declared_count) in file order.
    active:     dict prefix -> list of (id, title, priority) in index order.
    tombstones: set of struck-through IDs.
    """
    # -- Spec Files table: file <-> prefix mapping + declared per-file counts.
    spec_files: list[tuple[str, str, int]] = []
    declared_total: int | None = None
    file_row = re.compile(
        r"^\|\s*\[(\d{2}-[a-z0-9-]+\.md)\]\([^)]*\)\s*\|\s*([A-Z]+)\s*\|.*\|\s*(\d+)\s*\|\s*$"
    )
    total_row = re.compile(r"^\|\s*\*\*Total\*\*\s*\|.*\*\*(\d+)\*\*\s*\|\s*$")
    for line in text.splitlines():
        m = file_row.match(line)
        if m:
            spec_files.append((m.group(1), m.group(2), int(m.group(3))))
            continue
        m = total_row.match(line)
        if m and declared_total is None:
            declared_total = int(m.group(1))
    if not spec_files:
        fail(f"could not parse the Spec Files table in {SPEC_INDEX}")
    if declared_total is None:
        fail(f"could not parse the **Total** row of the Spec Files table in {SPEC_INDEX}")

    # -- Alphabetical Cross-Reference Index: the authoritative per-ID rows.
    section_start = text.find("## Alphabetical Cross-Reference Index")
    if section_start < 0:
        fail(f"'## Alphabetical Cross-Reference Index' heading not found in {SPEC_INDEX}")
    rest = text[section_start:]
    end = re.search(r"\n## (?!#)", rest[1:])
    section = rest[: end.start() + 1] if end else rest

    active: dict[str, list[tuple[str, str, str]]] = {}
    tombstones: set[str] = set()
    current_prefix: str | None = None
    tomb_cell = re.compile(r"^~~\s*([A-Z]+-\d+)\s*~~")
    id_cell = re.compile(r"^([A-Z]+-\d+)$")
    for line in section.splitlines():
        h = re.match(r"^### ([A-Z]+) — ", line)
        if h:
            current_prefix = h.group(1)
            active.setdefault(current_prefix, [])
            continue
        if current_prefix is None or not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        first = cells[0]
        if first in ("ID", "") or set(first) <= {"-", " "}:
            continue  # header / separator rows
        m = tomb_cell.match(first)
        if m:
            tombstones.add(m.group(1))
            continue
        m = id_cell.match(first)
        if m:
            rid = m.group(1)
            if not rid.startswith(current_prefix + "-"):
                fail(f"{rid} listed under the {current_prefix} section of {SPEC_INDEX}")
            active[current_prefix].append((rid, cells[1], cells[2]))

    # -- consistency checks: the parse must agree with the index's own counts.
    total = sum(len(v) for v in active.values())
    if total != EXPECTED_ACTIVE:
        per = ", ".join(f"{p}={len(v)}" for p, v in sorted(active.items()))
        fail(
            f"parsed {total} active requirements from {SPEC_INDEX}, expected "
            f"{EXPECTED_ACTIVE} ({per}; tombstones excluded: {sorted(tombstones)}). "
            f"If the spec index legitimately changed, update EXPECTED_ACTIVE in "
            f"scripts/spec-coverage-matrix.py in the same change."
        )
    if declared_total != EXPECTED_ACTIVE:
        fail(
            f"the Spec Files table in {SPEC_INDEX} declares a total of "
            f"{declared_total}, expected {EXPECTED_ACTIVE}"
        )
    for fname, prefix, declared in spec_files:
        got = len(active.get(prefix, []))
        if got != declared:
            fail(
                f"{SPEC_INDEX}: {fname} declares {declared} {prefix} requirements "
                f"but the cross-reference index lists {got}"
            )
    if set(p for _, p, _ in spec_files) != set(active):
        fail(
            f"prefix mismatch between the Spec Files table "
            f"({sorted(p for _, p, _ in spec_files)}) and the cross-reference "
            f"index ({sorted(active)}) in {SPEC_INDEX}"
        )
    return spec_files, active, tombstones


# --------------------------------------------------------------------------
# Lean sources: declarations (for validation) and ID mentions (input (c))
# --------------------------------------------------------------------------

def strip_lean_comments(src: str) -> str:
    """Remove Lean block comments (nested, incl. /-- and /-!) and -- line
    comments so doc prose never masquerades as a declaration."""
    out: list[str] = []
    i, n, depth = 0, len(src), 0
    while i < n:
        two = src[i : i + 2]
        if two == "/-":
            depth += 1
            i += 2
        elif depth > 0 and two == "-/":
            depth -= 1
            i += 2
        elif depth > 0:
            i += 1
        elif two == "--":
            while i < n and src[i] != "\n":
                i += 1
        else:
            out.append(src[i])
            i += 1
    return "".join(out)


def lean_sources() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for p in sorted(LEAN_DIR.rglob("*.lean")):
        if any(part in EXCLUDED_DIR_NAMES for part in p.parts):
            continue
        files[p] = p.read_text(encoding="utf-8")
    if not files:
        fail(f"no .lean sources found under {LEAN_DIR}")
    return files


# --------------------------------------------------------------------------
# (b) lean/proof-coverage.json — validated annotation layer
# --------------------------------------------------------------------------

def load_proof_coverage(active_ids: set[str], tombstones: set[str],
                        decls_by_file: dict[Path, set[str]]):
    """Return dict id -> list of (theorem_name, fragment)."""
    try:
        data = json.loads(PROOF_COVERAGE.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"{PROOF_COVERAGE} not found")
    except json.JSONDecodeError as e:
        fail(f"{PROOF_COVERAGE} is not valid JSON: {e}")
    theorems = data.get("theorems")
    if not isinstance(theorems, list):
        fail(f'{PROOF_COVERAGE}: top-level "theorems" must be a list')

    proven: dict[str, list[tuple[str, str]]] = {}
    for i, entry in enumerate(theorems):
        where = f"{PROOF_COVERAGE} theorems[{i}]"
        if not isinstance(entry, dict):
            fail(f"{where}: entry must be an object")
        name = entry.get("name")
        module = entry.get("module")
        spec_ids = entry.get("specIds")
        if not isinstance(name, str) or not name:
            fail(f'{where}: missing or empty "name"')
        if not isinstance(module, str) or not module:
            fail(f'{where} ({name}): missing or empty "module"')
        if not isinstance(spec_ids, list) or not spec_ids:
            fail(f'{where} ({name}): "specIds" must be a non-empty list')

        module_path = LEAN_DIR / module
        if module_path not in decls_by_file:
            fail(f"{where} ({name}): module {module} does not exist under {LEAN_DIR}")
        if name not in decls_by_file[module_path]:
            fail(
                f"{where}: dangling theorem name {name!r} — no `theorem {name}` "
                f"or `lemma {name}` declaration found in lean/{module}"
            )

        for j, sid in enumerate(spec_ids):
            swhere = f"{where} ({name}) specIds[{j}]"
            if not isinstance(sid, dict):
                fail(f"{swhere}: must be an object")
            rid = sid.get("id")
            fragment = sid.get("fragment")
            if not isinstance(rid, str) or not rid:
                fail(f'{swhere}: missing or empty "id"')
            if rid not in active_ids:
                kind = "a removed/tombstoned" if rid in tombstones else "not an active"
                fail(f"{swhere}: {rid} is {kind} spec ID per {SPEC_INDEX}")
            if not isinstance(fragment, str) or not fragment.strip():
                fail(f"{swhere} ({rid}): missing or empty \"fragment\"")
            proven.setdefault(rid, []).append((name, fragment.strip()))
    return proven


# --------------------------------------------------------------------------
# (d) per-language test greps
# --------------------------------------------------------------------------

def _mentioned_ids(paths, active_ids: set[str]) -> set[str]:
    found: set[str] = set()
    for p in paths:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            fail(f"cannot read {p}: {e}")
        found.update(m for m in SPEC_ID_RE.findall(text) if m in active_ids)
    return found


def _walk(root: Path, suffix: str):
    if not root.is_dir():
        return
    for p in sorted(root.rglob(f"*{suffix}")):
        if any(part in EXCLUDED_DIR_NAMES for part in p.parts):
            continue
        yield p


def collect_test_mentions(active_ids: set[str]) -> dict[str, set[str]]:
    java_files = list(_walk(REPO / "java" / "src" / "test", ".java"))
    ts_files = list(_walk(REPO / "typescript" / "tests", ".ts"))
    py_files = list(_walk(REPO / "python" / "tests", ".py"))

    rust_files: list[Path] = []
    for p in _walk(REPO / "rust", ".rs"):
        parts = p.parts
        if "tests" in parts:
            rust_files.append(p)
        elif "src" in parts:
            if RUST_CFG_TEST_RE.search(p.read_text(encoding="utf-8", errors="replace")):
                rust_files.append(p)

    for lang, files in (("java", java_files), ("typescript", ts_files),
                        ("rust", rust_files), ("python", py_files)):
        if not files:
            fail(f"no {lang} test files found — check the {lang} test glob")

    return {
        "java": _mentioned_ids(java_files, active_ids),
        "typescript": _mentioned_ids(ts_files, active_ids),
        "rust": _mentioned_ids(rust_files, active_ids),
        "python": _mentioned_ids(py_files, active_ids),
    }


# --------------------------------------------------------------------------
# output
# --------------------------------------------------------------------------

def md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def render(spec_files, active, proven, lean_refs, tests) -> str:
    langs = ("java", "typescript", "rust", "python")
    all_ids = [rid for _, prefix, _ in spec_files for rid, _, _ in active[prefix]]
    n = len(all_ids)
    assert n == EXPECTED_ACTIVE, f"internal error: rendering {n} rows, expected {EXPECTED_ACTIVE}"

    proven_ids = set(proven)
    ref_only = {rid for rid in all_ids if rid in lean_refs and rid not in proven_ids}
    untested = [rid for rid in all_ids if not any(rid in tests[l] for l in langs)]

    out: list[str] = []
    out.append(GENERATED_HEADER)
    out.append("")
    out.append("# Spec Proof/Test Coverage Matrix")
    out.append("")
    out.append(
        "Per active requirement of [`spec/00-index.md`](00-index.md): the Lean theorems "
        "that prove a stated *fragment* of it (from the hand-maintained, validated "
        "[`lean/proof-coverage.json`](../lean/proof-coverage.json)), whether the Lean "
        "sources merely mention the ID in comments, and per-language test references."
    )
    out.append("")
    out.append(
        f"Column semantics: a {CHECK_MARK} in a test column means \"referenced by ≥ 1 "
        f"test file\" in that language — a spec-ID citation, **not** a semantic "
        f"coverage guarantee. **Lean ref** {CHECK_MARK} means the ID appears in "
        f"`lean/**/*.lean` comments (grep), independent of — and weaker than — "
        f"the validated **Lean proof** column. Each Lean proof cell carries its honest "
        f"scope fragment; anything not stated there is not claimed "
        f"(see [`lean/README.md`](../lean/README.md) for the development's scope)."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- Active requirements: **{n}**")
    out.append(
        f"- Proven in Lean (≥ 1 validated theorem fragment): **{len(proven_ids)}**"
    )
    out.append(
        f"- Referenced in Lean comments only (mention without a validated theorem "
        f"mapping): **{len(ref_only)}**"
    )
    out.append(
        "- Referenced by ≥ 1 test file: "
        + ", ".join(f"{l} **{len(tests[l])}**" for l in langs)
    )
    out.append(
        f"- Untested anywhere (no test-file reference in any language): "
        f"**{len(untested)}**"
    )
    out.append("")

    for fname, prefix, _ in spec_files:
        out.append(f"## {fname} — {prefix}")
        out.append("")
        out.append("| ID | Lean proof (theorem + fragment) | Lean ref | java | typescript | rust | python |")
        out.append("|----|---------------------------------|----------|------|------------|------|--------|")
        for rid, _title, _prio in active[prefix]:
            if rid in proven:
                proof_cell = "<br>".join(
                    f"`{name}` — {md_escape(fragment)}"
                    for name, fragment in proven[rid]
                )
            else:
                proof_cell = DASH
            cells = [
                rid,
                proof_cell,
                CHECK_MARK if rid in lean_refs else DASH,
                *(CHECK_MARK if rid in tests[l] else DASH for l in langs),
            ]
            out.append("| " + " | ".join(cells) + " |")
        out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--update", action="store_true",
                      help="rewrite spec/coverage-matrix.md in place")
    mode.add_argument("--check", action="store_true",
                      help="verify spec/coverage-matrix.md is up to date; exit 1 "
                           "if stale (the default)")
    args = ap.parse_args()

    spec_files, active, tombstones = parse_spec_index(
        SPEC_INDEX.read_text(encoding="utf-8")
    )
    active_ids = {rid for rows in active.values() for rid, _, _ in rows}

    sources = lean_sources()
    stripped = {p: strip_lean_comments(src) for p, src in sources.items()}
    decls_by_file = {p: set(DECL_RE.findall(s)) for p, s in stripped.items()}

    proven = load_proof_coverage(active_ids, tombstones, decls_by_file)
    lean_refs = {
        m for src in sources.values() for m in SPEC_ID_RE.findall(src)
        if m in active_ids
    }
    tests = collect_test_mentions(active_ids)

    content = render(spec_files, active, proven, lean_refs, tests)

    if args.update:
        OUTPUT.write_text(content, encoding="utf-8")
        print(
            f"spec-coverage-matrix: wrote {OUTPUT.relative_to(REPO)} "
            f"({EXPECTED_ACTIVE} requirements)"
        )
        return 0

    # Default is verify — like the sibling scripts/lean-fidelity-check.py, a
    # bare invocation must never rewrite a tracked file.
    if not OUTPUT.exists():
        sys.stderr.write(
            f"spec-coverage-matrix: {OUTPUT} does not exist; run "
            f"scripts/spec-coverage-matrix.py --update to generate it\n"
        )
        return 1
    on_disk = OUTPUT.read_text(encoding="utf-8")
    if on_disk == content:
        print(f"spec-coverage-matrix: {OUTPUT.relative_to(REPO)} is up to date")
        return 0
    diff = list(difflib.unified_diff(
        on_disk.splitlines(), content.splitlines(),
        fromfile=f"{OUTPUT.relative_to(REPO)} (committed)",
        tofile=f"{OUTPUT.relative_to(REPO)} (regenerated)",
        lineterm="",
    ))
    sys.stderr.write(
        f"spec-coverage-matrix: {OUTPUT.relative_to(REPO)} is STALE "
        f"({sum(1 for l in diff if l.startswith('-') and not l.startswith('---'))} removed / "
        f"{sum(1 for l in diff if l.startswith('+') and not l.startswith('+++'))} added lines). "
        f"Regenerate with: python3 scripts/spec-coverage-matrix.py --update\n"
    )
    head = diff[:60]
    sys.stderr.write("\n".join(head) + "\n")
    if len(diff) > len(head):
        sys.stderr.write(f"... ({len(diff) - len(head)} more diff lines)\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
